<a href="https://colab.research.google.com/github/Dewmi-2003/Machine-Learning/blob/main/ML_Practical_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [58]:
import pandas as pd

In [59]:
df=pd.read_csv("/popular_shows_dataset.csv")

In [60]:
print(df)

                                                 title  year   revenue  \
0                                              Hoppers  2026  29000000
1                                     Reminders of Him  2026  18000000
2                                            undertone  2026   9300000
3                                             Scream 7  2026   8400000
4                                                 GOAT  2026   4700000
..                                                 ...   ...       ...
995                                         The Bride!  2026   2100000
996                            Kiki's Delivery Service  1989   1700000
997                                "Wuthering Heights"  2026   1700000
998  Teenage Mutant Ninja Turtles II: The Secret of...  1991   1500000
999                                          Crime 101  2026   1100000

        imdb_id  tmdb_id  trakt_id
0    tt26443616  1327819   1085761
1    tt33714084  1367642   1116720
2    tt35892608  1480387   1213506
3    tt27047903  1159559    934134
4    tt27613895  1297842   1057839
..          ...      ...       ...
995  tt30851137  1159831    934595
996   tt0097814    16859     10314
997  tt32897959  1316092   1077273
998   tt0103060     1497       991
999  tt32430579  1171145    944042

[1000 rows x 6 columns]

In [61]:
print(df.to_string())

                                                       title  year   revenue     imdb_id  tmdb_id  trakt_id
0                                                    Hoppers  2026  29000000  tt26443616  1327819   1085761
1                                           Reminders of Him  2026  18000000  tt33714084  1367642   1116720
2                                                  undertone  2026   9300000  tt35892608  1480387   1213506
3                                                   Scream 7  2026   8400000  tt27047903  1159559    934134
4                                                       GOAT  2026   4700000  tt27613895  1297842   1057839
5                                                 The Bride!  2026   2100000  tt30851137  1159831    934595
6                                    Kiki's Delivery Service  1989   1700000   tt0097814    16859     10314
7                                        "Wuthering Heights"  2026   1700000  tt32897959  1316092   1077273
8    Teenage Mutant Ninja Turtles II: The Secret of the Ooze  1991   1500000   tt0103060     1497       991
9                                                  Crime 101  2026   1100000  tt32430579  1171145    944042
10                                                   Hoppers  2026  29000000  tt26443616  1327819   1085761
11                                          Reminders of Him  2026  18000000  tt33714084  1367642   1116720
12                                                 undertone  2026   9300000  tt35892608  1480387   1213506
13                                                  Scream 7  2026   8400000  tt27047903  1159559    934134
14                                                      GOAT  2026   4700000  tt27613895  1297842   1057839
15                                                The Bride!  2026   2100000  tt30851137  1159831    934595
16                                   Kiki's Delivery Service  1989   1700000   tt0097814    16859     10314
17                                       "Wuthering Heights"  2026   1700000  tt32897959  1316092   1077273
18   Teenage Mutant Ninja Turtles II: The Secret of the Ooze  1991   1500000   tt0103060     1497       991
19                                                 Crime 101  2026   1100000  tt32430579  1171145    944042
20                                                   Hoppers  2026  29000000  tt26443616  1327819   1085761
21                                          Reminders of Him  2026  18000000  tt33714084  1367642   1116720
22                                                 undertone  2026   9300000  tt35892608  1480387   1213506
23                                                  Scream 7  2026   8400000  tt27047903  1159559    934134
24                                                      GOAT  2026   4700000  tt27613895  1297842   1057839
25                                                The Bride!  2026   2100000  tt30851137  1159831    934595
26                                   Kiki's Delivery Service  1989   1700000   tt0097814    16859     10314
27                                       "Wuthering Heights"  2026   1700000  tt32897959  1316092   1077273
28   Teenage Mutant Ninja Turtles II: The Secret of the Ooze  1991   1500000   tt0103060     1497       991
29                                                 Crime 101  2026   1100000  tt32430579  1171145    944042
30                                                   Hoppers  2026  29000000  tt26443616  1327819   1085761
31                                          Reminders of Him  2026  18000000  tt33714084  1367642   1116720
32                                                 undertone  2026   9300000  tt35892608  1480387   1213506
33                                                  Scream 7  2026   8400000  tt27047903  1159559    934134
34                                                      GOAT  2026   4700000  tt27613895  1297842   1057839
35                                                The Bride!  2026   2100000  tt30851137  1159831    934595
36                                   Kiki's Delivery Service  1989   1700000   tt0097814    16859     10314
37                                       "Wuthering Heights"  2026   1700000  tt32897959  1316092   1077273
38   Teenage Mutant Ninja Turtles II: The Secret of the Ooze  1991   1500000   tt0103060     1497       991
39                                                 Crime 101  2026   1100000  tt32430579  1171145    944042
40                                                   Hoppers  2026  29000000  tt26443616  1327819   1085761
41                                          Reminders of Him  2026  18000000  tt33714084  1367642   1116720
42                                                 undertone  2026   9300000  tt35892608  1480387   1213506
43                                                  Scream 7  2026   8400000  tt27047903  1159559    934134
44                                                      GOAT  2026   4700000  tt27613895  1297842   1057839
45                                                The Bride!  2026   2100000  tt30851137  1159831    934595
46                                   Kiki's Delivery Service  1989   1700000   tt0097814    16859     10314
47                                       "Wuthering Heights"  2026   1700000  tt32897959  1316092   1077273
48   Teenage Mutant Ninja Turtles II: The Secret of the Ooze  1991   1500000   tt0103060     1497       991
49                                                 Crime 101  2026   1100000  tt32430579  1171145    944042
50                                                   Hoppers  2026  29000000  tt26443616  1327819   1085761
51                                          Reminders of Him  2026  18000000  tt33714084  1367642   1116720
52                                                 undertone  2026   9300000  tt35892608  1480387   1213506
53                                                  Scream 7  2026   8400000  tt27047903  1159559    934134
54                                                      GOAT  2026   4700000  tt27613895  1297842   1057839
55                                                The Bride!  2026   2100000  tt30851137  1159831    934595
56                                   Kiki's Delivery Service  1989   1700000   tt0097814    16859     10314
57                                       "Wuthering Heights"  2026   1700000  tt32897959  1316092   1077273
58   Teenage Mutant Ninja Turtles II: The Secret of the Ooze  1991   1500000   tt0103060     1497       991
59                                                 Crime 101  2026   1100000  tt32430579  1171145    944042
60                                                   Hoppers  2026  29000000  tt26443616  1327819   1085761
61                                          Reminders of Him  2026  18000000  tt33714084  1367642   1116720
62                                                 undertone  2026   9300000  tt35892608  1480387   1213506
63                                                  Scream 7  2026   8400000  tt27047903  1159559    934134
64                                                      GOAT  2026   4700000  tt27613895  1297842   1057839
65                                                The Bride!  2026   2100000  tt30851137  1159831    934595
66                                   Kiki's Delivery Service  1989   1700000   tt0097814    16859     10314
67                                       "Wuthering Heights"  2026   1700000  tt32897959  1316092   1077273
68   Teenage Mutant Ninja Turtles II: The Secret of the Ooze  1991   1500000   tt0103060     1497       991
69                                                 Crime 101  2026   1100000  tt32430579  1171145    944042
70                                                   Hoppers  2026  29000000  tt26443616  1327819   1085761
71                                          Reminders of Him  2026  18000000  tt33714084  1367642   1116720
72                                                 undertone  2026   9300000  tt35892608  1480387   1213506
73                                                  Scream 7  2026   8400000  tt27047903  1159559    934134
74                                                      GOAT  2026   4700000  tt27613895  1297842   1057839
75                                                The Bride!  2026   2100000  tt30851137  1159831    934595
76                                   Kiki's Delivery Service  1989   1700000   tt0097814    16859     10314
77                                       "Wuthering Heights"  2026   1700000  tt32897959  1316092   1077273
78   Teenage Mutant Ninja Turtles II: The Secret of the Ooze  1991   1500000   tt0103060     1497       991
79                                                 Crime 101  2026   1100000  tt32430579  1171145    944042
80                                                   Hoppers  2026  29000000  tt26443616  1327819   1085761
81                                          Reminders of Him  2026  18000000  tt33714084  1367642   1116720
82                                                 undertone  2026   9300000  tt35892608  1480387   1213506
83                                                  Scream 7  2026   8400000  tt27047903  1159559    934134
84                                                      GOAT  2026   4700000  tt27613895  1297842   1057839
85                                                The Bride!  2026   2100000  tt30851137  1159831    934595
86                                   Kiki's Delivery Service  1989   1700000   tt0097814    16859     10314
87                                       "Wuthering Heights"  2026   1700000  tt32897959  1316092   1077273
88   Teenage Mutant Ninja Turtles II: The Secret of the Ooze  1991   1500000   tt0103060     1497       991
89                                                 Crime 101  2026   1100000  tt32430579  1171145    944042
90                                                   Hoppers  2026  29000000  tt26443616  1327819   1085761
91                                          Reminders of Him  2026  18000000  tt33714084  1367642   1116720
92                                                 undertone  2026   9300000  tt35892608  1480387   1213506
93                                                  Scream 7  2026   8400000  tt27047903  1159559    934134
94                                                      GOAT  2026   4700000  tt27613895  1297842   1057839
95                                                The Bride!  2026   2100000  tt30851137  1159831    934595
96                                   Kiki's Delivery Service  1989   1700000   tt0097814    16859     10314
97                                       "Wuthering Heights"  2026   1700000  tt32897959  1316092   1077273
98   Teenage Mutant Ninja Turtles II: The Secret of the Ooze  1991   1500000   tt0103060     1497       991
99                                                 Crime 101  2026   1100000  tt32430579  1171145    944042
100                                                  Hoppers  2026  29000000  tt26443616  1327819   1085761
101                                         Reminders of Him  2026  18000000  tt33714084  1367642   1116720
102                                                undertone  2026   9300000  tt35892608  1480387   1213506
103                                                 Scream 7  2026   8400000  tt27047903  1159559    934134
104                                                     GOAT  2026   4700000  tt27613895  1297842   1057839
105                                               The Bride!  2026   2100000  tt30851137  1159831    934595
106                                  Kiki's Delivery Service  1989   1700000   tt0097814    16859     10314
107                                      "Wuthering Heights"  2026   1700000  tt32897959  1316092   1077273
108  Teenage Mutant Ninja Turtles II: The Secret of the Ooze  1991   1500000   tt0103060     1497       991
109                                                Crime 101  2026   1100000  tt32430579  1171145    944042
110                                                  Hoppers  2026  29000000  tt26443616  1327819   1085761
111                                         Reminders of Him  2026  18000000  tt33714084  1367642   1116720
112                                                undertone  2026   9300000  tt35892608  1480387   1213506
113                                                 Scream 7  2026   8400000  tt27047903  1159559    934134
114                                                     GOAT  2026   4700000  tt27613895  1297842   1057839
115                                               The Bride!  2026   2100000  tt30851137  1159831    934595
116                                  Kiki's Delivery Service  1989   1700000   tt0097814    16859     10314
117                                      "Wuthering Heights"  2026   1700000  tt32897959  1316092   1077273
118  Teenage Mutant Ninja Turtles II: The Secret of the Ooze  1991   1500000   tt0103060     1497       991
119                                                Crime 101  2026   1100000  tt32430579  1171145    944042
120                                                  Hoppers  2026  29000000  tt26443616  1327819   1085761
121                                         Reminders of Him  2026  18000000  tt33714084  1367642   1116720
122                                                undertone  2026   9300000  tt35892608  1480387   1213506
123                                                 Scream 7  2026   8400000  tt27047903  1159559    934134
124                                                     GOAT  2026   4700000  tt27613895  1297842   1057839
125                                               The Bride!  2026   2100000  tt30851137  1159831    934595
126                                  Kiki's Delivery Service  1989   1700000   tt0097814    16859     10314
127                                      "Wuthering Heights"  2026   1700000  tt32897959  1316092   1077273
128  Teenage Mutant Ninja Turtles II: The Secret of the Ooze  1991   1500000   tt0103060     1497       991
129                                                Crime 101  2026   1100000  tt32430579  1171145    944042
130                                                  Hoppers  2026  29000000  tt26443616  1327819   1085761
131                                         Reminders of Him  2026  18000000  tt33714084  1367642   1116720
132                                                undertone  2026   9300000  tt35892608  1480387   1213506
133                                                 Scream 7  2026   8400000  tt27047903  1159559    934134
134                                                     GOAT  2026   4700000  tt27613895  1297842   1057839
135                                               The Bride!  2026   2100000  tt30851137  1159831    934595
136                                  Kiki's Delivery Service  1989   1700000   tt0097814    16859     10314
137                                      "Wuthering Heights"  2026   1700000  tt32897959  1316092   1077273
138  Teenage Mutant Ninja Turtles II: The Secret of the Ooze  1991   1500000   tt0103060     1497       991
139                                                Crime 101  2026   1100000  tt32430579  1171145    944042
140                                                  Hoppers  2026  29000000  tt26443616  1327819   1085761
141                                         Reminders of Him  2026  18000000  tt33714084  1367642   1116720
142                                                undertone  2026   9300000  tt35892608  1480387   1213506
143                                                 Scream 7  2026   8400000  tt27047903  1159559    934134
144                                                     GOAT  2026   4700000  tt27613895  1297842   1057839
145                                               The Bride!  2026   2100000  tt30851137  1159831    934595
146                                  Kiki's Delivery Service  1989   1700000   tt0097814    16859     10314
147                                      "Wuthering Heights"  2026   1700000  tt32897959  1316092   1077273
148  Teenage Mutant Ninja Turtles II: The Secret of the Ooze  1991   1500000   tt0103060     1497       991
149                                                Crime 101  2026   1100000  tt32430579  1171145    944042
150                                                  Hoppers  2026  29000000  tt26443616  1327819   1085761
151                                         Reminders of Him  2026  18000000  tt33714084  1367642   1116720
152                                                undertone  2026   9300000  tt35892608  1480387   1213506
153                                                 Scream 7  2026   8400000  tt27047903  1159559    934134
154                                                     GOAT  2026   4700000  tt27613895  1297842   1057839
155                                               The Bride!  2026   2100000  tt30851137  1159831    934595
156                                  Kiki's Delivery Service  1989   1700000   tt0097814    16859     10314
157                                      "Wuthering Heights"  2026   1700000  tt32897959  1316092   1077273
158  Teenage Mutant Ninja Turtles II: The Secret of the Ooze  1991   1500000   tt0103060     1497       991
159                                                Crime 101  2026   1100000  tt32430579  1171145    944042
160                                                  Hoppers  2026  29000000  tt26443616  1327819   1085761
161                                         Reminders of Him  2026  18000000  tt33714084  1367642   1116720
162                                                undertone  2026   9300000  tt35892608  1480387   1213506
163                                                 Scream 7  2026   8400000  tt27047903  1159559    934134
164                                                     GOAT  2026   4700000  tt27613895  1297842   1057839
165                                               The Bride!  2026   2100000  tt30851137  1159831    934595
166                                  Kiki's Delivery Service  1989   1700000   tt0097814    16859     10314
167                                      "Wuthering Heights"  2026   1700000  tt32897959  1316092   1077273
168  Teenage Mutant Ninja Turtles II: The Secret of the Ooze  1991   1500000   tt0103060     1497       991
169                                                Crime 101  2026   1100000  tt32430579  1171145    944042
170                                                  Hoppers  2026  29000000  tt26443616  1327819   1085761
171                                         Reminders of Him  2026  18000000  tt33714084  1367642   1116720
172                                                undertone  2026   9300000  tt35892608  1480387   1213506
173                                                 Scream 7  2026   8400000  tt27047903  1159559    934134
174                                                     GOAT  2026   4700000  tt27613895  1297842   1057839
175                                               The Bride!  2026   2100000  tt30851137  1159831    934595
176                                  Kiki's Delivery Service  1989   1700000   tt0097814    16859     10314
177                                      "Wuthering Heights"  2026   1700000  tt32897959  1316092   1077273
178  Teenage Mutant Ninja Turtles II: The Secret of the Ooze  1991   1500000   tt0103060     1497       991
179                                                Crime 101  2026   1100000  tt32430579  1171145    944042
180                                                  Hoppers  2026  29000000  tt26443616  1327819   1085761
181                                         Reminders of Him  2026  18000000  tt33714084  1367642   1116720
182                                                undertone  2026   9300000  tt35892608  1480387   1213506
183                                                 Scream 7  2026   8400000  tt27047903  1159559    934134

In [62]:
df.head()

              title  year   revenue     imdb_id  tmdb_id  trakt_id
0           Hoppers  2026  29000000  tt26443616  1327819   1085761
1  Reminders of Him  2026  18000000  tt33714084  1367642   1116720
2         undertone  2026   9300000  tt35892608  1480387   1213506
3          Scream 7  2026   8400000  tt27047903  1159559    934134
4              GOAT  2026   4700000  tt27613895  1297842   1057839

In [63]:
df.shape

(1000, 6)

In [64]:
df.columns

Index(['title', 'year', 'revenue', 'imdb_id', 'tmdb_id', 'trakt_id'], dtype='object')

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   title     1000 non-null   object
 1   year      1000 non-null   int64
 2   revenue   1000 non-null   int64
 3   imdb_id   1000 non-null   object
 4   tmdb_id   1000 non-null   int64
 5   trakt_id  1000 non-null   int64
dtypes: int64(4), object(2)
memory usage: 47.0+ KB

In [66]:
df.tail()

,title,year,revenue,imdb_id,tmdb_id,trakt_id
995,The Bride!,2026,2100000,tt30851137,1159831,934595
996,Kiki's Delivery Service,1989,1700000,tt0097814,16859,10314
997,"""Wuthering Heights""",2026,1700000,tt32897959,1316092,1077273
998,Teenage Mutant Ninja Turtles II: The Secret of...,1991,1500000,tt0103060,1497,991
999,Crime 101,2026,1100000,tt32430579,1171145,944042

In [67]:
df.head(10)

,title,year,revenue,imdb_id,tmdb_id,trakt_id
0,Hoppers,2026,29000000,tt26443616,1327819,1085761
1,Reminders of Him,2026,18000000,tt33714084,1367642,1116720
2,undertone,2026,9300000,tt35892608,1480387,1213506
3,Scream 7,2026,8400000,tt27047903,1159559,934134
4,GOAT,2026,4700000,tt27613895,1297842,1057839
5,The Bride!,2026,2100000,tt30851137,1159831,934595
6,Kiki's Delivery Service,1989,1700000,tt0097814,16859,10314
7,"""Wuthering Heights""",2026,1700000,tt32897959,1316092,1077273
8,Teenage Mutant Ninja Turtles II: The Secret of...,1991,1500000,tt0103060,1497,991
9,Crime 101,2026,1100000,tt32430579,1171145,944042

In [68]:
df.describe()

              year       revenue       tmdb_id      trakt_id
count  1000.000000  1.000000e+03  1.000000e+03  1.000000e+03
mean   2018.800000  7.750000e+06  1.029867e+06  8.375175e+05
std      14.414152  8.705877e+06  5.195836e+05  4.246083e+05
min    1989.000000  1.100000e+06  1.497000e+03  9.910000e+02
25%    2026.000000  1.700000e+06  1.159559e+06  9.341340e+05
50%    2026.000000  3.400000e+06  1.234494e+06  1.000940e+06
75%    2026.000000  9.300000e+06  1.327819e+06  1.085761e+06
max    2026.000000  2.900000e+07  1.480387e+06  1.213506e+06

##Selecting Columns

In [69]:
df['title']

0                                                Hoppers
1                                       Reminders of Him
2                                              undertone
3                                               Scream 7
4                                                   GOAT
                             ...
995                                           The Bride!
996                              Kiki's Delivery Service
997                                  "Wuthering Heights"
998    Teenage Mutant Ninja Turtles II: The Secret of...
999                                            Crime 101
Name: title, Length: 1000, dtype: object

In [70]:
df[["title","year","revenue"]]

                                                 title  year   revenue
0                                              Hoppers  2026  29000000
1                                     Reminders of Him  2026  18000000
2                                            undertone  2026   9300000
3                                             Scream 7  2026   8400000
4                                                 GOAT  2026   4700000
..                                                 ...   ...       ...
995                                         The Bride!  2026   2100000
996                            Kiki's Delivery Service  1989   1700000
997                                "Wuthering Heights"  2026   1700000
998  Teenage Mutant Ninja Turtles II: The Secret of...  1991   1500000
999                                          Crime 101  2026   1100000

[1000 rows x 3 columns]

##Selecting Rows

In [71]:
df.loc[0]

title          Hoppers
year              2026
revenue       29000000
imdb_id     tt26443616
tmdb_id        1327819
trakt_id       1085761
Name: 0, dtype: object

In [74]:
df.iloc[0:5]

              title  year   revenue     imdb_id  tmdb_id  trakt_id
0           Hoppers  2026  29000000  tt26443616  1327819   1085761
1  Reminders of Him  2026  18000000  tt33714084  1367642   1116720
2         undertone  2026   9300000  tt35892608  1480387   1213506
3          Scream 7  2026   8400000  tt27047903  1159559    934134
4              GOAT  2026   4700000  tt27613895  1297842   1057839

##Using lables/Conditions

In [75]:
df.loc[0]

title          Hoppers
year              2026
revenue       29000000
imdb_id     tt26443616
tmdb_id        1327819
trakt_id       1085761
Name: 0, dtype: object

In [78]:
df[df['revenue']>=29000000]

       title  year   revenue     imdb_id  tmdb_id  trakt_id
0    Hoppers  2026  29000000  tt26443616  1327819   1085761
10   Hoppers  2026  29000000  tt26443616  1327819   1085761
20   Hoppers  2026  29000000  tt26443616  1327819   1085761
30   Hoppers  2026  29000000  tt26443616  1327819   1085761
40   Hoppers  2026  29000000  tt26443616  1327819   1085761
..       ...   ...       ...         ...      ...       ...
950  Hoppers  2026  29000000  tt26443616  1327819   1085761
960  Hoppers  2026  29000000  tt26443616  1327819   1085761
970  Hoppers  2026  29000000  tt26443616  1327819   1085761
980  Hoppers  2026  29000000  tt26443616  1327819   1085761
990  Hoppers  2026  29000000  tt26443616  1327819   1085761

[100 rows x 6 columns]

In [77]:
df[df['year']==2026]

                   title  year   revenue     imdb_id  tmdb_id  trakt_id
0                Hoppers  2026  29000000  tt26443616  1327819   1085761
1       Reminders of Him  2026  18000000  tt33714084  1367642   1116720
2              undertone  2026   9300000  tt35892608  1480387   1213506
3               Scream 7  2026   8400000  tt27047903  1159559    934134
4                   GOAT  2026   4700000  tt27613895  1297842   1057839
..                   ...   ...       ...         ...      ...       ...
993             Scream 7  2026   8400000  tt27047903  1159559    934134
994                 GOAT  2026   4700000  tt27613895  1297842   1057839
995           The Bride!  2026   2100000  tt30851137  1159831    934595
997  "Wuthering Heights"  2026   1700000  tt32897959  1316092   1077273
999            Crime 101  2026   1100000  tt32430579  1171145    944042

[800 rows x 6 columns]

## Filtering Data

In [80]:
df[df["title"]=="Crime 101"]

         title  year  revenue     imdb_id  tmdb_id  trakt_id
9    Crime 101  2026  1100000  tt32430579  1171145    944042
19   Crime 101  2026  1100000  tt32430579  1171145    944042
29   Crime 101  2026  1100000  tt32430579  1171145    944042
39   Crime 101  2026  1100000  tt32430579  1171145    944042
49   Crime 101  2026  1100000  tt32430579  1171145    944042
..         ...   ...      ...         ...      ...       ...
959  Crime 101  2026  1100000  tt32430579  1171145    944042
969  Crime 101  2026  1100000  tt32430579  1171145    944042
979  Crime 101  2026  1100000  tt32430579  1171145    944042
989  Crime 101  2026  1100000  tt32430579  1171145    944042
999  Crime 101  2026  1100000  tt32430579  1171145    944042

[100 rows x 6 columns]

In [87]:
df[(df['revenue']>=29000000)&(df['year']=="2026")]

Empty DataFrame
Columns: [title, year, revenue, imdb_id, tmdb_id, trakt_id]
Index: []

##Handling missing values

In [88]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   title     1000 non-null   object
 1   year      1000 non-null   int64
 2   revenue   1000 non-null   int64
 3   imdb_id   1000 non-null   object
 4   tmdb_id   1000 non-null   int64
 5   trakt_id  1000 non-null   int64
dtypes: int64(4), object(2)
memory usage: 47.0+ KB

In [89]:
df.isnull

<bound method DataFrame.isnull of                                                  title  year   revenue  \
0                                              Hoppers  2026  29000000
1                                     Reminders of Him  2026  18000000
2                                            undertone  2026   9300000
3                                             Scream 7  2026   8400000
4                                                 GOAT  2026   4700000
..                                                 ...   ...       ...
995                                         The Bride!  2026   2100000
996                            Kiki's Delivery Service  1989   1700000
997                                "Wuthering Heights"  2026   1700000
998  Teenage Mutant Ninja Turtles II: The Secret of...  1991   1500000
999                                          Crime 101  2026   1100000

        imdb_id  tmdb_id  trakt_id
0    tt26443616  1327819   1085761
1    tt33714084  1367642   1116720
2    tt35892608  1480387   1213506
3    tt27047903  1159559    934134
4    tt27613895  1297842   1057839
..          ...      ...       ...
995  tt30851137  1159831    934595
996   tt0097814    16859     10314
997  tt32897959  1316092   1077273
998   tt0103060     1497       991
999  tt32430579  1171145    944042

[1000 rows x 6 columns]>

##Remove missing values

In [90]:
df.dropna()

,title,year,revenue,imdb_id,tmdb_id,trakt_id
0,Hoppers,2026,29000000,tt26443616,1327819,1085761
1,Reminders of Him,2026,18000000,tt33714084,1367642,1116720
2,undertone,2026,9300000,tt35892608,1480387,1213506
3,Scream 7,2026,8400000,tt27047903,1159559,934134
4,GOAT,2026,4700000,tt27613895,1297842,1057839
...,...,...,...,...,...,...
995,The Bride!,2026,2100000,tt30851137,1159831,934595
996,Kiki's Delivery Service,1989,1700000,tt0097814,16859,10314
997,"""Wuthering Heights""",2026,1700000,tt32897959,1316092,1077273
998,Teenage Mutant Ninja Turtles II: The Secret of...,1991,1500000,tt0103060,1497,991
999,Crime 101,2026,1100000,tt32430579,1171145,944042

##Fill missing values

In [91]:
df.fillna(0)

,title,year,revenue,imdb_id,tmdb_id,trakt_id
0,Hoppers,2026,29000000,tt26443616,1327819,1085761
1,Reminders of Him,2026,18000000,tt33714084,1367642,1116720
2,undertone,2026,9300000,tt35892608,1480387,1213506
3,Scream 7,2026,8400000,tt27047903,1159559,934134
4,GOAT,2026,4700000,tt27613895,1297842,1057839
...,...,...,...,...,...,...
995,The Bride!,2026,2100000,tt30851137,1159831,934595
996,Kiki's Delivery Service,1989,1700000,tt0097814,16859,10314
997,"""Wuthering Heights""",2026,1700000,tt32897959,1316092,1077273
998,Teenage Mutant Ninja Turtles II: The Secret of...,1991,1500000,tt0103060,1497,991
999,Crime 101,2026,1100000,tt32430579,1171145,944042

In [92]:
df['revenue'].fillna(df['revenue'].mean())

0      29000000
1      18000000
2       9300000
3       8400000
4       4700000
         ...
995     2100000
996     1700000
997     1700000
998     1500000
999     1100000
Name: revenue, Length: 1000, dtype: int64