<a href="https://colab.research.google.com/github/Dewmi-2003/Machine-Learning/blob/main/ML_Practical_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import pandas as pd

In [39]:
from sklearn.linear_model import LinearRegression

In [40]:
from sklearn.model_selection import train_test_split

In [41]:
model=LinearRegression()

In [42]:
df=pd.read_csv("/student_marks.csv")

In [43]:
X=df[['StudyHours','Attendance','Assignments','SleepHours']]
y=df['Marks']

In [44]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [45]:
print(df)

    StudyHours  Attendance  Assignments  SleepHours  Marks
0            1          70            3           7     52
1            2          73            4           8     60
2            3          76            5           7     65
3            4          79            6           8     73
4            5          82            7           7     78
..         ...         ...          ...         ...    ...
95          12          76            7           8     99
96           1          79            8           7     62
97           2          82            9           8     70
98           3          85           10           7     76
99           4          88           11           8     83

[100 rows x 5 columns]

In [46]:
df.head()

   StudyHours  Attendance  Assignments  SleepHours  Marks
0           1          70            3           7     52
1           2          73            4           8     60
2           3          76            5           7     65
3           4          79            6           8     73
4           5          82            7           7     78

In [47]:
df.shape

(100, 5)

In [48]:
df.columns

Index(['StudyHours', 'Attendance', 'Assignments', 'SleepHours', 'Marks'], dtype='object')

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   StudyHours   100 non-null    int64
 1   Attendance   100 non-null    int64
 2   Assignments  100 non-null    int64
 3   SleepHours   100 non-null    int64
 4   Marks        100 non-null    int64
dtypes: int64(5)
memory usage: 4.0 KB

In [50]:
df.describe()

       StudyHours  Attendance  Assignments  SleepHours       Marks
count  100.000000  100.000000   100.000000  100.000000  100.000000
mean     6.340000   84.580000     8.820000    7.500000   85.400000
std      3.496665    8.947862     3.715596    0.502519   12.131435
min      1.000000   70.000000     3.000000    7.000000   52.000000
25%      3.000000   77.000000     6.000000    7.000000   75.750000
50%      6.000000   84.500000     9.000000    7.500000   87.000000
75%      9.000000   92.000000    12.000000    8.000000   99.000000
max     12.000000  100.000000    15.000000    8.000000   99.000000

In [51]:
df["StudyHours"]

0      1
1      2
2      3
3      4
4      5
      ..
95    12
96     1
97     2
98     3
99     4
Name: StudyHours, Length: 100, dtype: int64

In [52]:
df[["StudyHours","Attendance"]]

    StudyHours  Attendance
0            1          70
1            2          73
2            3          76
3            4          79
4            5          82
..         ...         ...
95          12          76
96           1          79
97           2          82
98           3          85
99           4          88

[100 rows x 2 columns]

In [53]:
df["StudyHours"].mean()

np.float64(6.34)

In [54]:
df["Attendance"].max()

100

In [55]:
df.corr()

             StudyHours  Attendance  Assignments  SleepHours     Marks
StudyHours     1.000000    0.067565    -0.105642    0.143714  0.874239
Attendance     0.067565    1.000000     0.019578   -0.040436  0.285284
Assignments   -0.105642    0.019578     1.000000   -0.005410  0.252595
SleepHours     0.143714   -0.040436    -0.005410    1.000000  0.157407
Marks          0.874239    0.285284     0.252595    0.157407  1.000000

In [56]:
model.fit(X_train,y_train)

LinearRegression()

In [57]:
y_pred=model.predict(X_test)
print(y_pred)

[ 84.49996326  86.84922729  84.02266027  83.42825839  77.85114633
 100.72867403  81.80423027  79.21631474 106.42288497  79.45496624
  75.15541334  87.32653028 101.44462851  88.7119069   96.75538188
  73.7607553   74.35515717  71.18212119  78.08979783 107.37749095]

In [59]:
prediction = model.predict([[5,90,10,7]])
print(prediction)

[83.62723716]

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [63]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test,y_pred)
print("MAE:",mae)

MAE: 2.079816872941867

In [64]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test,y_pred)
print("MSE:",mse)

MSE: 8.835382862593836

In [65]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test,y_pred)
print("R2 Score:",r2)

R2 Score: 0.9033618674622642